config/routes.rb
Certification::Application.routes.draw do 
  resources :sections

  resources :tests

	root "sessions#new"
	
  get "home", to: "static_pages#home"
  get "static_pages/help"
  get "overview", to: "static_pages#overview"
  
  get "/mc_question", to: "questions#new_mc", as: "new_mc_question"
  get "/tf_question", to: "questions#new_tf", as: "new_tf_question"
  post "/mc_question", to: "questions#create"
  post "/tf_question", to: "questions#create"
  post "/tests/count_questions", to: "tests#count_questions"
  
  get "/newgen", to: "tests#newgen", as: "newgen_test"
  post "/newgen", to: "tests#creategen"
  
  get "/print/:id", to: "tests#print", as: 'print'
  get "/new_form", to: "scores#new_form"
  post "/new_form", to: "scores#new"
  post "scores/time", to: "scores#time"
  
  resources :answers

  resources :products

  resources :questions
  
  resources :tests

  resources :users
  
  resources :prints
  
  resources :scores
  
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signin', 	to: "sessions#new",				via: "get"
  match '/signout', to: "sessions#destroy",		via: "delete"
  
  match '/reset',            to: 'sessions#reset',                   via: "get"
  match '/reset_password',   to: 'sessions#reset_password',          via: "get"
  match '/reset',            to: 'sessions#reset',                   via: "post"
  match '/reset_password',   to: 'sessions#reset_password',          via: "post"

  

end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers, dependent: :destroy
	has_many :question_tests
	has_many :tests, through: :question_tests
	belongs_to :user
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:option].blank? }, :allow_destroy => true
  
  attr_accessor :ip_video_telephony_product_id, :enterprise_gateways_product_id, :ip_video_surveillance_product_id, :ip_voice_product_id, :consumer_atas_product_id, :ip_pbx_product_id 
  
	#default_scope -> { order('created_at ASC') }
	
  @category_check = ['ip_voice', 'ip_pbx', 'ip_video_surveillance', 'ip_video_telephony', 'consumer_atas', 'enterprise_gateways'] 
  @section_check =  ['Please Select a Section', 'Select a section']
  
  validates :content, presence: true
  validates :product_id, presence: true
  validates :section, presence: true
  validates_exclusion_of :section, in: @section_check
  validates :content, length: { maximum: 1000 }
  validates_inclusion_of :category, in: @category_check
  
      
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :permitted
  before_action :set_question, only: [:show, :edit, :update, :destroy]  
  before_action :signed_in_user, only: [:index, :edit, :show, :update, :destroy]


  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all  #.paginate(page: params[:page], per_page: 10)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  	@answer = Answer.new
  end

  # GET /questions/new
  def new
    @question = Question.new    
    @products = Product.all
  end
  def new_mc
    @sections = ProductSection.all
    @question = Question.new
    @product_sections = {}
    @sections.each do |section|
      @section_name = Section.find(section.section_id).name
      @product_sections["#{section.id}"] = {
        "product"          => "#{section.product_id}",
        "section"          => "#{@section_name}"
      }
    end
    4.times { @question.answers.build }
  end
  def new_tf
    @sections = ProductSection.all
    @question = Question.new
    @product_sections = {}
    @sections.each do |section|
      @section_name = Section.find(section.section_id).name
      @product_sections["#{section.id}"] = {
        "product"         => "#{section.product_id}",
        "section"         => "#{@section_name}"
      }
    end
    @question.answers.build
  end

  # GET /questions/1/edit
  def edit
    @sections = Section.all
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params) 
    @question.product_id = question_params["#{question_params[:category]}_product_id"]
    respond_to do |format|
      if @question.save
        @answer = Answer.find_by_question_id(@question.id)
        if @answer.option == "True"
          Answer.create(option: "False", question_id: @answer.question_id, correct: false)
        end
        if @answer.option == "False"
          Answer.create(option: "True", question_id: @answer.question_id, correct: false)
        end
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        if params[:question][:question_type] == "TF"
          format.html { render action: 'new_tf' }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        else
          format.html { render action: 'new_mc' }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
        
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.  
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:ip_pbx_product_id, :ip_video_telephony_product_id, :enterprise_gateways_product_id, :ip_video_surveillance_product_id, 
        :ip_voice_product_id, :consumer_atas_product_id, :section, :content, :question_type, :category, :product_id, :active, :user_id, 
        answers_attributes: [ :option, :correct, :question_id ] ).
      merge user_id: current_user.id
    end    
    
    # Before filters
    def signed_in_user
    	unless signed_in?
    		store_location
	    	redirect_to signin_url, notice: "Please sign in."
	    end
    end
    
    def admin_user
      unless admin_user?
        redirect_to root_url, notice: "Administrator permissions needed."
      end
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_edit_answer.html.erb
<%= form_for(@answer) do |f| %>

	<%= render 'shared/error_answers' %>

  <%= f.label :option %><br>
  <%= f.text_field :option, class: "input-lg", value: @answer.option %>

  <%= f.label :correct, "Correct Answer?" %><br>
  <%= f.check_box :correct %>

  <%= f.number_field :question_id, class: "input-lg", value: @question.id, style: "visibility: hidden" %>

  <%= f.submit "Update Answer", class: "btn btn-lg btn-primary" %>
  
  <p><%= @answer.id %></p>
    
<% end %>

<script>
	$(document).ready(function(){
		$("#answer_correct").bootstrapSwitch('onText', 'Yes');
		$("#answer_correct").bootstrapSwitch('offText', 'No');
		$("#answer_correct").bootstrapSwitch('size', 'large');
	});
</script>

app/views/questions/_new_answer.html.erb
<%= form_for(@answer) do |f| %>

	<%= render 'shared/error_answers' %>

  <%= f.label :option %><br>
  <%= f.text_field :option, class: "input-lg" %>

  <%= f.label :correct, "Correct Answer?" %><br>
  <%= f.check_box :correct %>

  <%= f.number_field :question_id, class: "input-lg", value: @question.id, style: "visibility: hidden" %>

  <%= f.submit "Add Answer", class: "btn btn-lg btn-primary" %>
    
<% end %>

<script>
	$(document).ready(function(){
		$("#answer_correct").bootstrapSwitch('onText', 'Yes');
		$("#answer_correct").bootstrapSwitch('offText', 'No');
		$("#answer_correct").bootstrapSwitch('size', 'large');
	});
</script>

app/views/questions/_question.html.erb
<tr>
	<td>
	<%= link_to "#{question.content}", question %>
	</td>
		<td style="text-align: center;"><small><%= question.category.upcase %></small></td>
		<td style="text-align: center;"><small><%= question.question_type %></small></td>
		<td style="text-align: center;"><small><%= Product.find(question.product_id).name %></small></td>
		<td style="text-align: center;"><small><%= question.section %></small></td>
		<td style="text-align: center;"><small><%= question.created_at.strftime("%b %d, %y") %></small></td>
		<td style="text-align: center;"><small><%= question.updated_at.strftime("%b %d, %y") %></small></td>
		<td style="text-align: center;">
		<%= link_to question do %>
			<i class="glyphicon glyphicon-zoom-in"></i>
		<% end %>
		<%= link_to edit_question_path(question) do %>
			<i class="glyphicon glyphicon-pencil"></i>
		<% end %>
		
		</td>
	
</tr>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= form_for(@question) do |f| %>

	<%= render 'shared/error_questions' %>
	<%= render 'form', f: f %>
	
	<%= f.submit "Update Question", class: "btn btn-lg btn-primary" %>
	
<% end %>

<hr />

<%= link_to 'Back', @question %>

app/views/questions/new_mc.html.erb
<style>
#ip_voice, #ip_video_surveillance, #ip_video_telephony, #consumer_atas, #enterprise_gateways, #ip_pbx
    {
        display:none;
    }
</style>

<h1>New Multiple Choice Question</h1>
<%= link_to 'Back', questions_path %>
<%= form_for @question, url: new_mc_question_path(@question) do |f| %>

	<%= render 'shared/error_questions' %>

  <%#= render 'form', f: f %>
  <%= f.select :question_type, [["Multiple Choice", "MC"]], {class: "form-control input-lg"}, style: "visibility: hidden" %>
  
  <%= f.label :content, "Question" %><br>
	<%= f.text_field :content, class: "input-lg" %>
	
	<%= f.label :category %><br>
	<%= f.select :category, [ ["IP Voice Telephony", "ip_voice"], ["IP Video Surveillance", "ip_video_surveillance"], ["IP Video Telephony", "ip_video_telephony"], ["Enterprise Gateways", "enterprise_gateways"], ["Consumer ATAs", "consumer_atas"], ["IP PBX", "ip_pbx"] ], {prompt: "Select Category"}, class: "input-lg", :id => "category" %>
	
	<div id="ip_voice">
	<%= f.label :product_id %><br>
	<%= f.collection_select :ip_voice_product_id, Product.where({ category: "ip_voice" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg product", id: "question_product_id1"} %>
	</div>
	
	<div id="ip_video_surveillance">
	<%= f.label :product_id %><br>
	<%= f.collection_select :ip_video_surveillance_product_id, Product.where({ category: "ip_video_surveillance" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id2"} %>
	</div>
	
	<div id="ip_video_telephony">
	<%= f.label :product_id %><br>
	<%= f.collection_select :ip_video_telephony_product_id, Product.where({ category: "ip_video_telephony" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id6"} %>
	</div>
	
	<div id="consumer_atas">
	<%= f.label :product_id %><br>
	<%= f.collection_select :consumer_atas_product_id, Product.where({ category: "consumer_atas" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id3"} %>
	</div>
	
	<div id="enterprise_gateways">
	<%= f.label :product_id %><br>
	<%= f.collection_select :enterprise_gateways_product_id, Product.where({ category: "enterprise_gateways" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id4"} %>
	</div>
	
	<div id="ip_pbx">
	<%= f.label :product_id %><br>
	<%= f.collection_select :ip_pbx_product_id, Product.where({ category: "ip_pbx" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id5"} %>
	</div>
	
	<!-- <input id="targetField" type="hidden" name="question[product_id]" id="product_id" value=""/> -->
	
	<%= f.label :section %><br>
	<%= f.select :section, options_for_select([ ["None", "None"] ]), {prompt: "Select a section"}, {class: "form-control input-lg" } %>
	
	
	<%= f.label :active %><br>
	<%= f.check_box :active %>

	
<h1>Answers</h1>
<%= f.fields_for :answers do |builder| %>
  	
  	<%= render 'four_answers', :f => builder %>

  <% end %>
  <%= f.submit "Create Question", class: "btn btn-lg btn-primary", id: "commit" %>
<% end %>
<br/>
<%= link_to 'Back', questions_path %>

<script>
	$(document).ready(function(){
		$("#question_active").bootstrapSwitch('onText', 'Active');
		$("#question_active").bootstrapSwitch('offText', 'Off');
		$("#question_active").bootstrapSwitch('size', 'large');
	});
</script>
<script>
var product_sections = <%= @product_sections.to_json.html_safe %>

$(document).ready(function(e) {
		$('#question_product_id1').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id1').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id2').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id2').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id3').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id3').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id4').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id4').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id5').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id5').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id6').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id6').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
	
        $('#category').change(function() {
            if ($('#category').val()== 'ip_voice')
            {
                $('#ip_video_surveillance').hide();
                $('#ip_video_telephony').hide();
                $('#consumer_atas').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').hide();
                $('#ip_voice').show();
            }
            else if ($('#category').val()== 'ip_video_surveillance')
            {
                $('#ip_voice').hide();
                $('#ip_video_telephony').hide();
                $('#consumer_atas').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').hide();
                $('#ip_video_surveillance').show();
            }
            else if ($('#category').val()== 'ip_video_telephony')
            {
                $('#ip_voice').hide();
                $('#ip_video_surveillance').hide();
                $('#consumer_atas').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').hide();
                $('#ip_video_telephony').show();
            }
            else if ($('#category').val()== 'consumer_atas')
            {
                $('#ip_voice').hide();
                $('#ip_video_surveillance').hide();
                $('#ip_video_telephony').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').hide();
                $('#consumer_atas').show();
            }
            else if ($('#category').val()== 'enterprise_gateways')
            {
                $('#ip_voice').hide();
                $('#ip_video_surveillance').hide();
                $('#ip_video_telephony').hide();
                $('#consumer_atas').hide();
                $('#ip_pbx').hide();
                $('#enterprise_gateways').show();
            }
            else if ($('#category').val()== 'ip_pbx')
            {
                $('#ip_voice').hide();
                $('#ip_video_surveillance').hide();
                $('#ip_video_telephony').hide();
                $('#consumer_atas').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').show();
            }
            

        });
});
</script>
<!--
	$(function(){
        
        var valueAssigned = false;
        $('.product').each(function(){
            if($(this).val())
            {
                $("[name='question[product_id]']").val($(this).val());
                valueAssigned = true;
                return;
            }
        });

        
    });
 Tell what is value
if(!valueAssigned)
        {
            alert('nothing selected');
        }
        else
        {
            alert("Value of the hidden field: " + $("#targetField").val());
        }
-->

app/views/questions/new_tf.html.erb
<style>
#ip_voice, #ip_video_surveillance, #ip_video_telephony, #consumer_atas, #enterprise_gateways, #ip_pbx
    {
        display:none;
    }
</style>

<h1>New True/False Question</h1>
<%= link_to 'Back', questions_path %>
<%= form_for @question, url: new_tf_question_path(@question) do |f| %>

	<%= render 'shared/error_questions' %>
	
  <%#= render 'form', f: f %>
  <%= f.select :question_type, [["True False", "TF"]], {class: "form-control input-lg"}, style: "visibility: hidden" %>
  
  <%= f.label :content, "Question" %><br>
	<%= f.text_field :content, class: "input-lg" %>
	
	<%= f.label :category %><br>
	<%= f.select :category, [ ["IP Voice Telephony", "ip_voice"], ["IP Video Surveillance", "ip_video_surveillance"], ["IP Video Telephony", "ip_video_telephony"], ["Enterprise Gateways", "enterprise_gateways"], ["Consumer ATAs", "consumer_atas"], ["IP PBX", "ip_pbx"] ], {prompt: "Select Category"}, class: "input-lg", :id => "category" %>
	
	<div id="ip_voice">
	<%= f.label :product_id %><br>
	<%= f.collection_select :ip_voice_product_id, Product.where({ category: "ip_voice" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id1"} %>
	</div>
	
	<div id="ip_video_surveillance">
	<%= f.label :product_id %><br>
	<%= f.collection_select :ip_video_surveillance_product_id, Product.where({ category: "ip_video_surveillance" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id2"} %>
	</div>
	
	<div id="ip_video_telephony">
	<%= f.label :product_id %><br>
	<%= f.collection_select :ip_video_telephony_product_id, Product.where({ category: "ip_video_telephony" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id6"} %>
	</div>
	
	<div id="consumer_atas">
	<%= f.label :product_id %><br>
	<%= f.collection_select :consumer_atas_product_id, Product.where({ category: "consumer_atas" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id3"} %>
	</div>
	
	<div id="enterprise_gateways">
	<%= f.label :product_id %><br>
	<%= f.collection_select :enterprise_gateways_product_id, Product.where({ category: "enterprise_gateways" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id4"} %>
	</div>
	
	<div id="ip_pbx">
	<%= f.label :product_id %><br>
	<%= f.collection_select :ip_pbx_product_id, Product.where({ category: "ip_pbx" }), :id, :name, {prompt: "Select a product"}, {class: "form-control input-lg", id: "question_product_id5"} %>
	</div>
	
	<!-- <input id="targetField" type="hidden" name="question[product_id]" value="0"/> -->
	
	<%= f.label :section %><br>
	<%= f.select :section, options_for_select([ ["None", "None"] ]), {prompt: "Select a section"}, {class: "form-control input-lg" } %>
	
	<%= f.label :active %><br>
	<%= f.check_box :active %>

	
	<%= f.fields_for :answers do |builder| %>
  	
  	<%= render 'tf_answers', :f => builder %>
		
  <% end %>
  
  <%= f.submit "Create Question", class: "btn btn-lg btn-primary", id: "commit", style: "margin-top: 45px;" %>

<% end %>
<br/>
<%= link_to 'Back', questions_path %>

<script>
	$(document).ready(function(){
		$("#question_active").bootstrapSwitch('onText', 'Active');
		$("#question_active").bootstrapSwitch('offText', 'Off');
		$("#question_active").bootstrapSwitch('size', 'large');
	});
</script>
<script>
var product_sections = <%= @product_sections.to_json.html_safe %>

$(document).ready(function(e) {
		$('#question_product_id1').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id1').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id2').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id2').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id3').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id3').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id4').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id4').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id5').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id5').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
		$('#question_product_id6').change(function(){
			$('#question_section').html("<option>Please Select a Section</option>");
			
			$.each( product_sections, function(){
				if (this.product == $('#question_product_id6').val())
				{
					
						$('#question_section').append("<option>" + this.section + "</option>");
				}
			});
		});
        $('#category').change(function() {
            if ($('#category').val()== 'ip_voice')
            {
                $('#ip_video_surveillance').hide();
                $('#ip_video_telephony').hide();
                $('#consumer_atas').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').hide();
                $('#ip_voice').show();
            }
            else if ($('#category').val()== 'ip_video_surveillance')
            {
                $('#ip_voice').hide();
                $('#ip_video_telephony').hide();
                $('#consumer_atas').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').hide();
                $('#ip_video_surveillance').show();
            }
            else if ($('#category').val()== 'ip_video_telephony')
            {
                $('#ip_voice').hide();
                $('#ip_video_surveillance').hide();
                $('#consumer_atas').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').hide();
                $('#ip_video_telephony').show();
            }
            else if ($('#category').val()== 'consumer_atas')
            {
                $('#ip_voice').hide();
                $('#ip_video_surveillance').hide();
                $('#ip_video_telephony').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').hide();
                $('#consumer_atas').show();
            }
            else if ($('#category').val()== 'enterprise_gateways')
            {
                $('#ip_voice').hide();
                $('#ip_video_surveillance').hide();
                $('#ip_video_telephony').hide();
                $('#consumer_atas').hide();
                $('#ip_pbx').hide();
                $('#enterprise_gateways').show();
            }
            else if ($('#category').val()== 'ip_pbx')
            {
                $('#ip_voice').hide();
                $('#ip_video_surveillance').hide();
                $('#ip_video_telephony').hide();
                $('#consumer_atas').hide();
                $('#enterprise_gateways').hide();
                $('#ip_pbx').show();
            }
            

        });
});
</script>
<!-- <script>
$(function(){
    $("#commit").on("click", function(){
        
        var valueAssigned = false;
        $('select').each(function(){
            if($(this).val())
            {
                $("[name='question[product_id]']").val($(this).val());
                valueAssigned = true;
                return;
            }
        });
		if(!valueAssigned)
        {
            alert('nothing selected');
        }
        else
        {
            alert("Value of the hidden field: " + $("#targetField").val());
        }	
    });
});
</script>
<!-- Tell what is value
if(!valueAssigned)
        {
            alert('nothing selected');
        }
        else
        {
            alert("Value of the hidden field: " + $("#targetField").val());
        }
-->

app/views/questions/show.html.erb
<% provide(:title, "Question Details") %>

<div class="row">
	<div class="col-md-9 col-md-offset-2">
		<h3>
			<%= @question.id %>. <%= @question.content %>
		</h3>
		
		<hr />
		
		<ul style="list-style: upper-latin; font-size: 1.1em">
		<% @question.answers.each do |answer| %>
			<%= render answer %>
		<% end %>
		<button class="btn btn-primary" data-toggle="modal" data-target="#addModal">Add Answer</button>
		</ul>
		<hr />
		<p>
		  <strong>Type:</strong>
		  <%= @question.question_type %>
		</p>
		
		<p>
		  <strong>Category:</strong>
		  <%= @question.category %>
		</p>
		
		<p>
		  <strong>Product:</strong>
		  <%= Product.find(@question.product_id).name %>
		</p>
		
		<p>
		  <strong>Section:</strong>
		  <%= @question.section %>
		</p>
		
		<p>
		  <strong>Active:</strong>
		  <%= @question.active %>
		</p>
	</div>
</div>

<hr />

<!-- Add Answer Modal -->
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="addModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    	<div class="modal-header">
    		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    		<h4 class="modal-title">New Answer</h4>
    	</div>
    	<div class="modal-body">
		    <%= render 'new_answer' %>
    	</div>
    </div>
  </div>
</div>

<!-- Edit Answer Modal -->
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="editModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    	<div class="modal-header">
    		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    		<h4 class="modal-title">Edit Answer</h4>
    	</div>
    	<div class="modal-body">
		    <%= render 'edit_answer' %>
    	</div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>