config/routes.rb
Certification::Application.routes.draw do 
  resources :sections

  resources :tests

	root "sessions#new"
	
  get "home", to: "static_pages#home"
  get "static_pages/help"
  get "overview", to: "static_pages#overview"
  
  get "/mc_question", to: "questions#new_mc", as: "new_mc_question"
  get "/tf_question", to: "questions#new_tf", as: "new_tf_question"
  post "/mc_question", to: "questions#create"
  post "/tf_question", to: "questions#create"
  post "/tests/count_questions", to: "tests#count_questions"
  
  get "/newgen", to: "tests#newgen", as: "newgen_test"
  post "/newgen", to: "tests#creategen"
  
  get "/print/:id", to: "tests#print", as: 'print'
  get "/new_form", to: "scores#new_form"
  post "/new_form", to: "scores#new"
  post "scores/time", to: "scores#time"
  
  resources :answers

  resources :products

  resources :questions
  
  resources :tests

  resources :users
  
  resources :prints
  
  resources :scores
  
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signin', 	to: "sessions#new",				via: "get"
  match '/signout', to: "sessions#destroy",		via: "delete"
  
  match '/reset',            to: 'sessions#reset',                   via: "get"
  match '/reset_password',   to: 'sessions#reset_password',          via: "get"
  match '/reset',            to: 'sessions#reset',                   via: "post"
  match '/reset_password',   to: 'sessions#reset_password',          via: "post"

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<div class="pull-right">Version 1.1.0</div>		
	</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to image_tag("your_logo.png", alt: "Exam Certification"), root_path, id: "logo" %>
			<nav>
				<ul class="nav navbar-nav pull-right">
					<% if signed_in? && permitted %>
					<li><%= link_to "Overview", root_path %></li>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Prepare Sections <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "1. Products", products_path %></li>
							<li class="divider"></li>
							<li><%= link_to "2. Test Sections", sections_path %></li>
						</ul>
					</li>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Prepare Tests <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "1. Questions", questions_path %></li>
							<li class="divider"></li>
							<li><%= link_to "2. Tests", tests_path %></li>
						</ul>
					</li>
					<li><%= link_to "Scores", scores_path %></li>					
					<% if admin_user? %>
						<li><%= link_to "Users", users_path %></li>
					  <% end %>
					  <li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
							</li>
						</ul>
					  </li>
					<% else %>
					  <% if signed_in? %>
					  <li><%= link_to "Home", scores_path %></li>
						<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
							</li>
						</ul>
					  </li>
					  <% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					  <% end %>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert #{bootstrap_class_for(key)}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>